spring:
  redis:
    host: localhost
    port: 6379
  session:
    store-type: redis
  datasource:
    url: jdbc:mysql://localhost:3306/poc_database?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.session_factory.statement_inspector: com.example.demo.application.DynamicCatalogNameInterceptor

  flyway:
    url: jdbc:mysql://localhost:3306
    user: root
    password: password
    default-schema: poc_database
